export const SAVE_COMMENT = 'SAVE_COMMENT';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const CHANGE_AUTH = 'CHANGE_AUTH';
export const GET_USER_LIST = 'GET_USER_LIST';
export const SAVE_USER_LIST = 'SAVE_USER_LIST';